### ISSUE TITLE
Is this branch deprecated?

### ISSUE THREAD

**Issue by yuhangwang** [craftr-build/creator#52]
The front page of your branch says "Deprecated. Old Prototype of a Meta Build System for Ninja", but I can still still very active development. Another branch "https://github.com/NiklasRosenstein/creator" is less active than this one. Which one is the official branch? Thanks.

**Comment by NiklasRosenstein** [comment]
Hey @yuhangwang, oh I totally forgot that I still have a fork of Creator on my account. Both are deprecated, development is continued on Craftr (https://github.com/craftr-build/craftr).

**Comment by yuhangwang** [comment]
I see. Thank you for the near URL. Your "Creator" is highlighted here (https://github.com/martine/ninja/wiki/List-of-generators-producing-ninja-build-files ).  Could you add a note on your Creator page about "Craftr", or make a suggestion to update Martine's list? Thanks.

**Comment by NiklasRosenstein** [comment]
Yes, I've updated the link in the Wiki. Thanks :)
